dist: trusty
sudo: required
language: c
env:
  global:
    - GAPROOT=$HOME/gap
    - COVDIR=coverage
    - NODE_OPTIONS=--max-old-space-size=4096

addons:
  apt:
    update: true

  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - libgmp-dev:i386
    - libreadline-dev:i386
    - gcc-multilib
    - g++-multilib
    - libzmq3-dev
    - libzmq3-dev:i386
    - python3
    - python3-pip
    - texlive-full

matrix:
  include:
    - env: CFLAGS="-O2"
      compiler: gcc

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - nvm install 14.5.0
  - nvm alias default 14.5.0
  - pyenv install 3.8.0
  - pyenv global 3.8.0
before_script:
  - scripts/prepare.sh
script:
  - scripts/tests.sh
after_success:
  - scripts/coverage.sh

deploy:
  provider: script
  script: bash scripts/release.sh
  skip_cleanup: true
  on:
    tags: true
