dist: trusty
sudo: required
language: c
env:
  global:
    - GAPROOT=$HOME/gap
    - COVDIR=coverage

addons:
  apt:
    update: true

  apt_packages:
    - nodejs
    - npm
    - libgmp-dev
    - libreadline-dev
    - libgmp-dev:i386
    - libreadline-dev:i386
    - gcc-multilib
    - g++-multilib
    - libzmq3-dev
    - libzmq3-dev:i386
    - python3
    - python3-pip
    - texlive-latex-recommended

matrix:
  include:
    - env: CFLAGS="-O2"
      compiler: gcc

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - scripts/prepare.sh
script:
  - scripts/tests.sh
after_success:
  - scripts/coverage.sh

deploy:
  provider: script
  script: bash scripts/release.sh
  skip_cleanup: true
  on:
    tags: true
